context:
  version: "1.1.4"

package:
  name: fish-lsp
  version: ${{ version | replace('-', '_') }}

source:
  url: https://registry.npmjs.org/fish-lsp/-/fish-lsp-${{ version }}.tgz
  sha256: d42edf4cb15f09b1e6bd96ddbf9a4954c11b24b504d1118d84bef4df414efa90

build:
  noarch: generic
  number: 0

requirements:
  build:
    - fish
    - nodejs
    - pnpm
    - pnpm-licenses
    - husky
  host:
    - nodejs
  run:
    - fish
    - nodejs

tests:
  - script:
      - npm list -g fish-lsp
      - fish-lsp --help
      - fish-lsp --version
      - "fish-lsp info | grep Version"
      - fish-lsp info
      - fish-lsp info --time-only
      - fish-lsp info --time-startup --no-warning
      - fish-lsp complete | fish --no-execute
      - fish-lsp env | fish --no-execute
      - echo 'set -lx foo bar' | fish-lsp info --dump-parse-tree
      - echo 'function myfunc; end' | fish-lsp info --dump-semantic-tokens

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: LSP implementation for the fish shell language
  homepage: https://github.com/ndonfris/fish-lsp
  repository: https://github.com/ndonfris/fish-lsp

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
